### ISSUE TITLE
Error retrieving number of liked posts from response object

### ISSUE THREAD

**Issue by jjkaye** [andresdavid90/tumblr-lks-downldr#1]
```
JJs-MacBook-Pro:Desktop jjkaye$ tumblr-lks-downldr -u 'jjkaye.tumblr.com' -1 1 -p 'TEXT'
Tumblr Blog: jjkaye.tumblr.com
Saving in: /Users/jjkaye/Desktop/TEXT/
Posts to download: undefined
Loading images list in memory. Please wait...
/usr/local/lib/node_modules/tumblr-lks-downldr/tumblr-lks-downldr.js:166
        for(var i = 0; i < likedPosts.length; i++){
                                     ^

TypeError: Cannot read property 'length' of undefined
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/tumblr-lks-downldr/tumblr-lks-downldr.js:166:38)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

If you notice in the attached code snippet, the `length` property is undefined. I'm not very familiar with the tumblr api or node so I'm not sure how far back to trace the error.

If this an error on my part, it might have to do with my permissions on my npm install or simply a command line error.

**Comment by robsalasco** [comment]
you have to use your own api key!

**Comment by andrscrrn** [comment]
Hey @jjkaye! Thanks for let me know about the bug and sorry for the delay for giving you a response.

Apparently the problem is that you don't have enabled the "Share post you like" option in your blog settings. You need to do it before running updating and running again the utility. I'm also updating the code in order to show the appropriate message for this case.

@robsalasco you don't need to do that.
